package com.greenbon.base.comm;

/**
 * 错误类型
 */
public enum BaseErrorEnum {
    ERR_DAO_RODO_INSERT,
    ERR_DAO_RODO_INSERTBATCH,
    ERR_DAO_RODO_UPDATE,
    ERR_DAO_RODO_UPDATEMAP,
    ERR_DAO_RODO_DELETEBYKEY,
    ERR_DAO_RODO_DELETE,
    ERR_DAO_RODO_DELETEBATCH,
    ERR_DAO_RODO_FETCH,
    ERR_DAO_RODO_QUERY,
    ERR_DAO_RODO_COUNT,
    ERR_DAO_RODO_LIST,
    ERR_DAO_RODO_PAGE,
    ERR_DAO_RODO_SQL_TEMPLATE
}
